{
 "title": "Tracker",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   { "name": "categories", "label": "Categories", "query": "SELECT name FROM categories" },
   {
    "name": "items",
    "label": "Items",
    "query": "SELECT DISTINCT(item) FROM spendings"
   }
  ]
 },
 "panels": [
  {
   "title": "Monthly Spending",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT to_char(s.date, 'YYYY/MM') AS \"month_year\", SUM(s.amount) \r\nFROM (\r\n  SELECT DISTINCT (spendings.id), spendings.amount, spendings.date, spendings.item\r\n  FROM spendings\r\n  JOIN spendings_categories ON spendings_categories.spending = spendings.id\r\n  JOIN categories ON categories.id = spendings_categories.category\r\n  WHERE categories.name IN ($categories)\r\n) AS s\r\n\r\nWHERE item in ($items)\r\nAND date BETWEEN '${__from:date:iso}' AND '${__to:date:iso}'\r\nGROUP BY month_year"
    }
   ]
  },
  {
   "title": "Spending per Item",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "LE" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT item, SUM(amount) \r\nFROM spendings \r\nWHERE item IN ( $items )\r\nAND date BETWEEN '${__from:date:iso}' AND '${__to:date:iso}'\r\nGROUP BY item"
    }
   ]
  },
  {
   "title": "Spending per Category",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "LE" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT name, SUM(amount) FROM \r\nspendings JOIN spendings_categories ON spendings.id = spendings_categories.spending\r\nJOIN categories ON categories.id = spendings_categories.category\r\nWHERE name IN ( $categories )\r\nAND date BETWEEN '${__from:date:iso}' AND '${__to:date:iso}'\r\nGROUP BY name"
    }
   ]
  },
  {
   "title": "Spending Percentage",
   "type": "piechart",
   "description": "Distribution of spending by category",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "p14" ] } },
   "targets": [
    {
     "rawSql": "WITH total_amount AS ( \r\n  SELECT SUM(amount) FROM public.spendings\r\n )\r\nSELECT name, (SUM(amount) / (SELECT * FROM total_amount)) * 100\r\nFROM total_amount, public.spendings\r\nJOIN public.spendings_categories ON spendings_categories.spending = spendings.id\r\nJOIN public.categories ON categories.id = spendings_categories.category\r\nWHERE name IN ( $categories )\r\nAND date BETWEEN '${__from:date:iso}' AND '${__to:date:iso}'\r\nGROUP BY name"
    }
   ]
  }
 ]
}